<?php

namespace App\Controller;

use App\Entity\Hebergement;
use App\Form\HebergementType;
use App\Repository\HebergementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/hebergement")
 */
class HebergementController extends Controller
{
    /**
     * @Route("/", name="hebergement_index", methods="GET")
     */
    public function index(HebergementRepository $hebergementRepository): Response
    {
        return $this->render('hebergement/index.html.twig', ['hebergements' => $hebergementRepository->findAll()]);
    }

    /**
     * @Route("/new", name="hebergement_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $hebergement = new Hebergement();
        $form = $this->createForm(HebergementType::class, $hebergement, array('is_new' => true));
        
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hebergement->setHebLat(10);
            $hebergement->setHebLong(10);
            $hebergement->setHebDateCreation(new \DateTime());
            $hebergement->setHebDateDeclaration(new \DateTime());
            $hebergement->setHebCerfa(123);
            $hebergement->setHebStatut('en cours');
            $hebergement->sethebNumDeclaration('Mairie321');
            
            $file = $hebergement->getHebPhoto1();
            
            // si on upload, on set avec nouvelle photo
            if($file != null) {
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            
                $file->move(
                    $this->getParameter('images_directory'),
                    $fileName
                );
                
                $hebergement->setHebPhoto1($fileName);    
            } 
            // si pas d'upload, on met photo par defaut
            else
            {
                $hebergement->setHebPhoto1('defaut-image.jpg');   
            }
            
            $em = $this->getDoctrine()->getManager();
            $em->persist($hebergement);
            $em->flush();

            return $this->redirectToRoute('dashboard_declarant');
        }

        return $this->render('hebergement/new.html.twig', [
            'hebergement' => $hebergement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="hebergement_show", methods="GET")
     */
    public function show(Hebergement $hebergement): Response
    {
        return $this->render('hebergement/show.html.twig', ['hebergement' => $hebergement]);
    }

    /**
     * @Route("/edit/{id}", name="hebergement_edit", methods="GET|POST")
     */
    public function edit(Request $request, Hebergement $hebergement): Response
    {
        $form = $this->createForm(HebergementType::class, $hebergement,array('is_edit' => true));
        
        // memoriser valeur de la bdd dans variable pour comparer avec l'upload
        $photo1 = $hebergement->getHebPhoto1();
        
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $file = $hebergement->getHebPhoto1();
            
            // si on upload
            if($file != null) {
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            
                $file->move(
                    $this->getParameter('images_directory'),
                    $fileName
                );
                
                $hebergement->setHebPhoto1($fileName);    
            } 
            // si pas d'upload
            else
            {
                $hebergement->setHebPhoto1($photo1);   
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('hebergement_edit', ['id' => $hebergement->getId()]);
           
        }

        return $this->render('hebergement/edit.html.twig', [
            'hebergement' => $hebergement,
            'form' => $form->createView(),
        ]);
    }
    
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/{id}", name="hebergement_delete", methods="DELETE")
     */
    public function delete(Request $request, Hebergement $hebergement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$hebergement->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($hebergement);
            $em->flush();
        }

        return $this->redirectToRoute('hebergement_index');
    }
}
